language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install mysqlclient psycopg2"
script: python manage.py test
env:
  - DJANGO_SETTINGS_MODULE=frekenbok.settings.test_sqlite
  - DJANGO_SETTINGS_MODULE=frekenbok.settings.test_mysql_travis
  - DJANGO_SETTINGS_MODULE=frekenbok.settings.test_postgres_travis