language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install mysql-connector"
script: python manage.py test
env:
  - DJANGO_SETTINGS_MODULE=frekenbok.settings.test_sqlite
  - DJANGO_SETTINGS_MODULE=frekenbok.settings.test_mysql
services:
  - mysql