image: python:3.5.1

pipelines:
    default:
        - step:
            script:
                - pip install -r requirements.txt
                - pip install django-autofixture # tests dependency
                - python manage.py test
