# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('opened', models.DateField(blank=True, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounter.AccountGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=50)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('source_value', models.DecimalField(blank=True, decimal_places=5, max_digits=50)),
                ('destination_value', models.DecimalField(blank=True, decimal_places=5, max_digits=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='accounter.Account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='accounter.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounter.AccountGroup'),
        ),
    ]
