# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expence'), ('account', 'Account')], default='account', max_length=30),
            preserve_default=False,
        ),
    ]
