# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0003_auto_20160218_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
