# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0004_account_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounter.Transaction'),
        ),
    ]
