# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True)),
                ('rgt', models.PositiveIntegerField(db_index=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True)),
                ('depth', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('type', models.IntegerField(choices=[(1, 'income'), (2, 'expense'), (3, 'account')], verbose_name='type')),
                ('opened', models.DateField(auto_now_add=True, null=True, verbose_name='date of open')),
                ('closed', models.DateField(blank=True, null=True, verbose_name='date of close')),
                ('credentials', models.TextField(blank=True, verbose_name='credentials')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='description')),
                ('file', models.FileField(upload_to='', verbose_name='file with image')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date and time')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Sheaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='sheaf')),
                ('currency', djmoney.models.fields.CurrencyField(default='RUB', max_length=3, verbose_name='currency')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheaves', to='accountant.Account', verbose_name='account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='amount')),
                ('currency', djmoney.models.fields.CurrencyField(default='RUB', max_length=3, verbose_name='currency')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accountant.Account', verbose_name='account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accountant.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accountant.Invoice', verbose_name='invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='sheaf',
            unique_together={('account', 'currency')},
        ),
    ]
