# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 15:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=Decimal('1'), max_digits=50, verbose_name='good quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('kg', 'kilos'), ('g', 'grams'), ('l', 'liters'), ('gal', 'gallons'), ('p', 'pounds')], default='u', max_length=255, verbose_name='unit of measurement'),
        ),
    ]
