# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=50, null=True, verbose_name='good quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(blank=True, choices=[('pcs', 'pieces'), ('kg', 'kilos'), ('g', 'grams'), ('l', 'liters'), ('gal', 'gallons'), ('p', 'pounds')], default=None, max_length=255, null=True, verbose_name='unit of measurement'),
        ),
    ]
