# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_quantity_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', verbose_name='file with image'),
        ),
        migrations.AlterField(
            model_name='document',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accountant.Invoice', verbose_name='invoice'),
        ),
    ]
